### ISSUE TITLE
Conditioning on baseline with different representation dimension

### ISSUE THREAD

**Issue by BigSquirrel2000** [john-hewitt/conditional-probing#2]
Hi !
In paper, in 2.3, you state that:

> we again train two probes; each is the concatenation of two representations of size d

And in README, there is written that:

> Conditional probing: measure only the aspects of property that aren't explainable by the **baseline of your choice.**

Just to be 100% sure: 
Is it methodologically correct to condition on baseline which has different representation size than main model?
e.g. I would like to have BERT base (d=768) as baseline and BERT large (d=1024) as main model.

**Comment by john-hewitt** [comment]
Thanks for the question! The sizes can differ.

In Section 2.3 of the paper, we incorrectly indicate that the sizes must be equal; this is true in the paper's experiments but need not be true in general. In Appendix A, we give a formal definition that does not have this requirement; see for example Example 1 as well, in which the different variables have different dimesionalities.

**Comment by BigSquirrel2000** [comment]
Thanks for answer !
